name: fault-profile-tool
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy >= 1.18.1
  - matplotlib >= 3.1.1
  - netcdf4 >= 1.4.2
  - ipython >= 7.9.0
  - scipy >= 1.3.1
  - rasterio >= 1.1.0
  - geopandas >= 0.6.1
  - jupyterlab >= 3.0.9
  - shapely == 1.8.5
  - pip
  - git
  - pip:
    - git+https://github.com/andy22b/fault-profile-tool/#subdirectory=src/fault-profile-tool
    - git+https://github.com/andy22b/fault-profile-tool/#subdirectory=src/icp_error

